name             "electrum"
maintainer       "Casey Link"
maintainer_email "unnamedrambler@gmail.com"
license          "GNU Affero General Public License"
description      "Installs/Configures an electrum server"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
recipe           "electrum", "Installs and configures an electrum server"
supports         "debian"
supports         "ubuntu"
depends          "python"
depends          "postgresql"
depends          "bitcoin-abe"
depends          "apt"
